name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Claude Code
title: "[BUG] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the sections below to help us understand and fix the issue.
        
        Before submitting, please check:
        - You're using the [latest version](https://www.npmjs.com/package/@anthropic-ai/claude-code?activeTab=versions) of Claude Code (`claude --version`) 
        - This issue hasn't already been reported by searching [existing issues](https://github.com/anthropics/claude-code/issues?q=is%3Aissue%20state%3Aopen%20label%3Abug).
        - This is a bug, not a feature request or support question
        
  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please confirm before submitting
      options:
        - label: I have searched [existing issues](https://github.com/anthropics/claude-code/issues?q=is%3Aissue%20state%3Aopen%20label%3Abug) and this hasn't been reported yet
          required: true
        - label: This is a single bug report (please file separate reports for different bugs)
          required: true
        - label: I am using the latest version of Claude Code
          required: true
          
  - type: textarea
    id: actual
    attributes:
      label: What's Wrong?
      description: Describe what's happening that shouldn't be
      placeholder: |
        When I try to create a Python file, Claude shows an error "EACCES: permission denied" and the file isn't created.
        
        The command fails immediately after accepting the file write permission...
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: What Should Happen?
      description: Describe the expected behavior
      placeholder: Claude should create a Python script file successfully without errors
    validations:
      required: true
      
  - type: textarea
    id: error_output
    attributes:
      label: Error Messages/Logs
      description: If you see any error messages, paste them here
      placeholder: |
        Paste any error output, stack traces, or relevant logs here.
        This will be automatically formatted as code.
      render: shell
    validations:
      required: false
      
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: |
        Please provide clear, numbered steps that anyone can follow to reproduce the issue.
        **Important**: Include any necessary code, file contents, or context needed to reproduce the bug.
        If the issue involves specific files or code, please create a minimal example.
      placeholder: |
        1. Create a file `test.py` with this content:
           ```python
           def hello():
               print("test")
           ```
        2. Run `claude "add type hints to test.py"`
        3. When prompted for file access, accept
        4. Error appears: "Unable to parse..."
        
        Note: The bug only happens with Python files containing...
    validations:
      required: true
      
  - type: dropdown
    id: model
    attributes:
      label: Claude Model
      description: Which model were you using? (Run `/model` to check)
      options:
        - Sonnet (default)
        - Opus
        - Not sure / Multiple models
        - Other
    validations:
      required: false
      
  - type: dropdown
    id: regression
    attributes:
      label: Is this a regression?
      description: Did this work in a previous version? 
      options:
        - "Yes, this worked in a previous version"
        - "No, this never worked"
        - "I don't know"
    validations:
      required: true
      
  - type: input
    id: working_version
    attributes:
      label: Last Working Version
      description: If this is a regression, which version last worked? This helps expedite a fix.
      placeholder: "e.g., 1.0.100"
    validations:
      required: false
      
  - type: input
    id: version
    attributes:
      label: Claude Code Version
      description: Run `claude --version` and paste the output
      placeholder: "e.g., 1.0.123 (Claude Code)"
    validations:
      required: true
      
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which API platform are you using?
      options:
        - Anthropic API
        - AWS Bedrock
        - Google Vertex AI
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Ubuntu/Debian Linux
        - Other Linux
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: terminal
    attributes:
      label: Terminal/Shell
      description: Which terminal are you using?
      options:
        - Terminal.app (macOS)
        - Warp
        - Cursor
        - iTerm2
        - IntelliJ IDEA terminal
        - VS Code integrated terminal
        - PyCharm terminal
        - Windows Terminal        
        - PowerShell
        - WSL (Windows Subsystem for Linux)
        - Xterm
        - Non-interactive/CI environment
        - Other
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: |
        Anything else that might help us understand the issue?
        - Screenshots (drag and drop images here)
        - Configuration files
        - Related files or code
        - Links to repositories demonstrating the issue
      placeholder: Any additional context, screenshots, or information...
    validations:
      required: false