name: ✨ Feature Request
description: Suggest a new feature or enhancement for Claude Code
title: "[FEATURE] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a feature!
        
        We love hearing ideas from our community. Please help us understand your use case by filling out the sections below.
        Before submitting, please check if this feature has already been requested.
        
  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      options:
        - label: I have searched [existing requests](https://github.com/anthropics/claude-code/issues?q=is%3Aissue%20label%3Aenhancement) and this feature hasn't been requested yet
          required: true
        - label: This is a single feature request (not multiple features)
          required: true
          
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        What problem are you trying to solve? Why do you need this feature?
        Focus on the problem, not the solution. Help us understand your workflow.
      placeholder: |
        I often need to work with multiple projects simultaneously, but Claude Code doesn't support...
        
        When I'm debugging code, I find it difficult to...
        
        The current workflow requires me to manually...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        How would you like this to work? Describe the ideal user experience.
        Be specific about how you'd interact with this feature.
      placeholder: |
        I'd like to be able to run `claude --workspace project1,project2` to...
        
        There should be a command or setting that allows...
        
        The interface should show...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: |
        What alternatives have you considered or tried?
        Are there workarounds you're currently using?
      placeholder: |
        I've tried using multiple terminal windows but...
        
        Currently I work around this by...
        
        Other tools solve this by...
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your workflow?
      options:
        - Critical - Blocking my work
        - High - Significant impact on productivity
        - Medium - Would be very helpful
        - Low - Nice to have
    validations:
      required: true
      
  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - CLI commands and flags
        - Interactive mode (TUI)
        - File operations
        - API and model interactions
        - MCP server integration
        - Performance and speed
        - Configuration and settings
        - Developer tools/SDK
        - Documentation
        - Other
    validations:
      required: true
      
  - type: textarea
    id: use_case
    attributes:
      label: Use Case Example
      description: |
        Provide a concrete, real-world example of when you'd use this feature.
        Walk us through a scenario step-by-step.
      placeholder: |
        Example scenario:
        1. I'm working on a React app with a Node.js backend
        2. I need to make changes to both frontend and backend
        3. With this feature, I could...
        4. This would save me time because...
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        - Screenshots or mockups of the proposed feature
        - Links to similar features in other tools
        - Technical considerations or constraints
        - Any other relevant information
      placeholder: Add any other context, mockups, or examples here...
    validations:
      required: false