name: 🤖 Model Behavior Issue
description: Report unexpected Claude model behavior, incorrect actions, or permission violations
title: "[MODEL] "
labels:
  - model
body:
  - type: markdown
    attributes:
      value: |
        ## Report Unexpected Model Behavior
        
        Use this template when Claude does something unexpected, makes unwanted changes, or behaves inconsistently with your instructions.
        
        **This is for:** Unexpected actions, file modifications outside scope, ignoring instructions, making assumptions
        **NOT for:** Crashes, API errors, or installation issues (use Bug Report instead)
        
  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please confirm before submitting
      options:
        - label: I have searched [existing issues](https://github.com/anthropics/claude-code/issues?q=is%3Aissue%20state%3Aopen%20label%3Amodel) for similar behavior reports
          required: true
        - label: This report does NOT contain sensitive information (API keys, passwords, etc.)
          required: true
          
  - type: dropdown
    id: behavior_type
    attributes:
      label: Type of Behavior Issue
      description: What category best describes the unexpected behavior?
      options:
        - Claude modified files I didn't ask it to modify
        - Claude accessed files outside the working directory
        - Claude ignored my instructions or configuration
        - Claude reverted/undid previous changes without asking
        - Claude made incorrect assumptions about my project
        - Claude refused a reasonable request
        - Claude's behavior changed between sessions
        - Subagent behaved unexpectedly
        - Other unexpected behavior
    validations:
      required: true
      
  - type: textarea
    id: what_you_asked
    attributes:
      label: What You Asked Claude to Do
      description: Provide the exact prompt or command you gave
      placeholder: |
        I asked: "Update the README.md file to add installation instructions"
        
        Or I ran: `claude "fix the bug in auth.js"`
    validations:
      required: true
      
  - type: textarea
    id: what_claude_did
    attributes:
      label: What Claude Actually Did
      description: Describe step-by-step what Claude did instead
      placeholder: |
        1. Claude read README.md
        2. Instead of updating it, Claude deleted the entire file
        3. Created a new README from scratch with different content
        4. Also modified package.json without being asked
        5. Changed .gitignore file
    validations:
      required: true
      
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should Claude have done?
      placeholder: |
        Claude should have:
        1. Read the existing README.md
        2. Added an "Installation" section
        3. Only modified that single file
        4. Not touched any other files
    validations:
      required: true
      
  - type: textarea
    id: files_affected
    attributes:
      label: Files Affected
      description: |
        List all files that were accessed or modified (even if you didn't expect them to be)
      placeholder: |
        Modified:
        - README.md (deleted and recreated)
        - package.json (version bumped - not requested)
        - .gitignore (added entries - not requested)
        
        Read (unexpectedly):
        - /Users/me/.ssh/config
        - ../../../parent-directory/secrets.env
      render: shell
    validations:
      required: false
      
  - type: dropdown
    id: permission_mode
    attributes:
      label: Permission Mode
      description: What permission settings were active?
      options:
        - Accept Edits was ON (auto-accepting changes)
        - Accept Edits was OFF (manual approval required)
        - I don't know / Not sure
    validations:
      required: true
      
  - type: dropdown
    id: reproducible
    attributes:
      label: Can You Reproduce This?
      description: Does this happen consistently?
      options:
        - Yes, every time with the same prompt
        - Sometimes (intermittent)
        - No, only happened once
        - Haven't tried to reproduce
    validations:
      required: true
      
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: If reproducible, provide minimal steps
      placeholder: |
        1. Create a new directory with a simple README.md
        2. Ask Claude Code to "improve the README"
        3. Claude will delete and recreate the file instead of editing
    validations:
      required: false
      
  - type: dropdown
    id: model
    attributes:
      label: Claude Model
      description: Which model were you using? (Run `/model` to check)
      options:
        - Sonnet
        - Opus
        - Haiku
        - Not sure
        - Other
    validations:
      required: true
      
  - type: textarea
    id: conversation_log
    attributes:
      label: Relevant Conversation
      description: |
        Include relevant parts of Claude's responses, especially where it explains what it's doing
      placeholder: |
        Claude said: "I'll help you update the README. Let me first delete the old one and create a fresh version..."
        
        [Then proceeded to delete without asking for confirmation]
      render: markdown
    validations:
      required: false
      
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How severe was the impact of this behavior?
      options:
        - Critical - Data loss or corrupted project
        - High - Significant unwanted changes
        - Medium - Extra work to undo changes
        - Low - Minor inconvenience
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: Claude Code Version
      description: Run `claude --version` and paste the output
      placeholder: "e.g., 1.0.123 (Claude Code)"
    validations:
      required: true
      
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which API platform are you using?
      options:
        - Anthropic API
        - AWS Bedrock
        - Google Vertex AI
        - Other
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        - Any patterns you've noticed
        - Similar behavior in other sessions
        - Specific file types or project structures that trigger this
        - Screenshots if relevant
      placeholder: |
        This seems to happen more often with:
        - Python projects
        - When there are multiple similar files
        - After long conversations
    validations:
      required: false